# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: OTGPremium/OTGPremium

build:
  stage: build
  script:
    - mkdir -p build && cd build
    - if [ ! "$(ls -A)" ]; then echo "build dir is empty"; cmake ..; fi
    - make -j $(nproc)
  artifacts:
    paths:
      - build/tfs
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    paths:
      - "build/*"

# run tests using the binary built before
# test:
#  stage: test
#  script:
#   - ./runmytests.sh
